### ISSUE TITLE
Sql Command

### ISSUE THREAD

**Issue by Normynator** [NRankedDev/JavaMyAdmin#26]

**Comment by Normynator** [comment]
@LegendSalocin , Wir sollten die SQLCommand funktion abhänig von der aktuell ausgewählten DB/Tabelle machen, weil man sonst immer 'dbname'.'tablename' machen muss und das rafft sonst wieder keiner

**Comment by nimueller** [comment]
@Normynator Kann man nicht den Befehl "USE <dbname>" benutzen?

Ansonsten können wir das dann von mir aus abhängig von der DB/Tabelle machen, dann manch ich ein Context-Menu (beim Rechtsklick) nen Eintrag für die Funktion. 
Also z.B.: "SQLCommand Line für <ausgewählte Database/Tabelle> öffnen"

**Comment by Normynator** [comment]
@LegendSalocin 
Seihe phpMyAdmin, da kann man "SQL Command" überall nutzen, also ohne eine DB/Table selected zu haben.
Wenn man keine DB selected hat muss man "dbname.tablename" nutzen.
Wenn man eine DB selected hat reicht es "tablename" zu nutzen.

Also bräuchte ich ne angabe wo man ca ist.
Bsp:
-Server: "SQL-Befehl(e) auf Server "127.0.0.1" ausführen:" (In der Box -> "   "(kein Cmd vorgeschlagen))

-DB: "SQL-Befehl(e) in Datenbank cdcol ausführen:" (In der Box -> "   "(kein Cmd vorgeschlagen))

-Table: "SQL-Befehl(e) in Tabelle cdcol.test ausführen:" (In der Box -> "SELECT \* FROM `test` WHERE 1"(CMD vorgeschlagen))

**Comment by nimueller** [comment]
@Normynator 
Methoden würden dann so aussehen (?):
- executeServerSQL(String sql)
- executeDatabaseSQL(String dbname, String sql)
- executeTableSQL(String dbname, String tablename, String sql)

Rückgabe wird dann aber umfangreich, da man in diesem Statement ja Abfragen machen kann.
Brauche da die columnnames und die Daten in den columns

**Comment by Normynator** [comment]
@LegendSalocin 
Alles zu erriechen über ".executeSQL(cmd)"

executeSQL(String cmd) : Table oder null (NULL wenn es ein update war, denn da bekommt man keine Tabelle zurück)

**Comment by nimueller** [comment]
@Normynator 
Bei der Methode, wenn ich die Lines aus der Table auslesen will (mit Table.getLines) kommt der Fehler:
`Table 'test.null' doesn't exist`

**Comment by nimueller** [comment]
@Normynator 
Problem noch nicht gefixt:
- Auf Server: `Database not selected.` [Eingegebener Cmd: `SELECT * FROM testdb.testtable;`]
- Auf Datenbank: `Table 'testtable.null' doesn't exist` [Eingegebener Cmd: `SELECT * FROM testtable;`]
- Bei einer selektieren Tabelle kann man eine andere mit SELECT ausgeben, hier geht's also.

Wäre auch nett, wenn es in Table die Methode isAbstract() geben würde, dann kann ich in der UI das editiern der Werte verbieten.

**Comment by Normynator** [comment]
isAbstract(), existierte war nur falsch benannt.
Server und Datenbank, sollten nun funktionieren, da dort einfach das isAbstract() fehlte
