### ISSUE TITLE
ALTER TABLE

### ISSUE THREAD

**Issue by nimueller** [NRankedDev/JavaMyAdmin#48]
- void addColumn(String columnName, String datatype, String length, boolean isNull, String index)
- void removeColumn(String columnName)
- void renameColumn(String oldColumnName, String newColumnName)

**Comment by nimueller** [comment]
@Normynator 
Wäre eine Methode zum Umbennen einer Tabelle auf die Schnelle noch möglich?

Methode: (in der Klasse Table)
- void renameTable(String newName)

**Comment by Normynator** [comment]
renameTable & renameDatabase 
094abf954ad750315bbbe6501f354d8213c6654a

**Comment by nimueller** [comment]
Es tritt ein Fehler beim Erstellen von Columns auf:
`com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') NOT NULL, ADD NONE (neueColumn)' at line 1`

**Comment by Normynator** [comment]
Erstellen der Columns prüfen ob ein Primary existiert, ansonsten gibt es einen Error wenn man einen 2. erstellen will.

**Comment by nimueller** [comment]
@Normynator 
Hab auch nen Bug gefunden: http://puu.sh/ltpyK/c7ac3e0bf3.png
Wenn ich ne Tabelle umbenenne gibt's nen Error.
Liegt der Fehler mit dem Primary auch da dran?

**Comment by nimueller** [comment]
@Normynator 
Es tritt immernoch der Fehler beim Erstellen von Columns auf:
`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') NOT NULL' at line 1`

Habe heraus gefunden, dass dies Auftritt, wenn man bei Length nichts angibt, also der String leer ist. Hilft das weiter?
