### ISSUE TITLE
Table.getDatabase()

### ISSUE THREAD

**Issue by nimueller** [NRankedDev/JavaMyAdmin#55]
@Normynator 
Wäre es möglich, die Methode
`Database getDatabase()`
in der Table Klasse zu erstellen?
Wenn die Table abstract ist, kann die Methode ja null zurückgeben.

**Comment by Normynator** [comment]
@LegendSalocin 
geht nur String getDatabase()

**Comment by nimueller** [comment]
@Normynator 
Jup. Ne Database wär aber besser.
Kannst mir die ja über DBManager.getInstance().getDB(database) zruückgeben.
Das is das Gute an dieser getInstance() Methode.
