### ISSUE TITLE
reload nach rename

### ISSUE THREAD

**Issue by Normynator** [NRankedDev/JavaMyAdmin#57]
Bei jeglichen "renames" muss danach die liste neu geladen werden

**Comment by Normynator** [comment]
siehe #48

**Comment by Normynator** [comment]
Korrektur, refreshs sollten komplett in source gemacht werden, also bitte wieder entfernen.

**Comment by nimueller** [comment]
@Normynator 
Wie soll das denn gehen?
Beim Reload erneure ich alle UI Elemente (z.B. TreeItems, TableColumns, usw.).
Ich greife nur auf die ArrayLists der Datenbanken und Tables zu und durchlaufe diese.
Dann müsstest du in source auf UI Elemente zugreifen, was ja gar keinen Sinn macht.
Außerdem müssten wir dann das halbe Projekt umschreiben.
